### ISSUE TITLE
create a few static templates

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/frontend#10]
- [ ] grocery list HTML template that looks good
- [ ] Meal planning HTML template that looks good

**Comment by atherdon** [comment]
I really like how these guys handled showcasing approach: https://slite.com/templates
if we'll be able to have something similar - i'll be very happy.

Btw, i know about cool showcasing template that was done by designmodo - maybe we can use them.
Buzz me before starting I'll create a better explanation of what exactly I want to have.

**Comment by politologu** [comment]
@atherdon the first we need to choose which group to choose one I mean here:
Team meetings
Design
Human Resources
Management
Startup
Product
Marketing
Customer Success
Development

before to go with template

**Comment by atherdon** [comment]
@politologu I don't get your question. please explain

**Comment by atherdon** [comment]
i wanted to 'steal' a main flow of showcasing templates. so pick any category and then you'll see a 'animated page' that i want to recreate. maybe this is an answer to your question

**Comment by politologu** [comment]
@atherdon yep so I thought

**Comment by atherdon** [comment]
tell me, if you started to work on this task

**Comment by politologu** [comment]
Which technologies we will use and how will looks our template, put any example template here?

**Comment by atherdon** [comment]
let's start from a plain HTML\CSS3\JS things. and later we'll jump into react. i know that you feel like not ready... But, i think i know the way :)
Hi :smile:

**Comment by atherdon** [comment]
Btw, i started to work on article, related to this repository. 
first part is published here: https://medium.com/groceristar/groceristar-roadmap-2-backend-frontend-separation-part-1-1de53a8240a9

**Comment by atherdon** [comment]
and there no exact 'template' rigth now. i mean all wil be changed on the
fly. so skip that part. think more about big picture. about how it'll be
animated, and other things. hope this is not a problem. if you want - just
put there a placeholder image. and we'll figure it out later.


On 25-Apr-2018 at 09:53 PM, Qazim Rama wrote:


Which technologies we will use and how will looks our template, put any
example template here?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/frontend/issues/10#issuecomment-384446249>,
or mute the thread

**Comment by atherdon** [comment]
@politologu  tell me, if these
![7e3b81b21b5bfc3a93c678e1d23e277f](https://user-images.githubusercontent.com/1469198/39280796-fa34da0a-4909-11e8-8655-c3a1dbba39dc.jpg)
![77fb77296e35233a3e131bcb5020f635](https://user-images.githubusercontent.com/1469198/39280800-fc99ea92-4909-11e8-8861-8386176980f5.jpg)
![dc718bf79f96b612e7d90994ed812a91](https://user-images.githubusercontent.com/1469198/39280802-01ea6a8a-490a-11e8-8c53-eab6c7bc15c3.jpg)


 templates are what you were requesting
![d27ef4845e8b40ebf504220539278f52](https://user-images.githubusercontent.com/1469198/39280791-f38bc8d0-4909-11e8-824b-6b74752e12f8.jpg)

**Comment by politologu** [comment]
before to get started are you thinking to create or transform these templates lists basically with html5 and css3 as for the beginning?

**Comment by atherdon** [comment]
i'm not sure how to answer this. just start - show me something(code) and
we'll decide our next steps. again, want to see some progress with you...


On 26-Apr-2018 at 09:58 AM, Qazim Rama wrote:


before to get started are you thinking to create or transform these
templates lists basically with html5 and css3 as for the beginning?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/frontend/issues/10#issuecomment-384583669>,
or mute the thread

**Comment by atherdon** [comment]
@politologu it's still not clear for me - are you working on this task? if yes - i'll assign it to you.
if you have something to show me - feel free. i'm curious about seeing your progress

**Comment by politologu** [comment]
I am working, will back soon

**Comment by atherdon** [comment]
still will be interested to know some deadlines.
as before - will continue to pushing you. so be ready :)
