### ISSUE TITLE
launchaco new version homepage 

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/frontend#14]
change homepage to new version.
Don't be worried about custom generated domain
add links to heroku logins
save main link to launchaco: https://www.launchaco.com/builder/GroceriStar

https://groceristar.launchaco.com/

and i'll be able to remove a lot of unnecessary shit from project folders

![startup website builder launchaco](https://user-images.githubusercontent.com/1469198/35333659-969bf50e-0120-11e8-81f9-f888e0c754e5.png)

**Comment by politologu** [comment]
@atherdon now is more beautifully more than before

**Comment by politologu** [comment]
@atherdon via launchaco will create a  new design web and be hosting(I mean is similarly as a WordPress or?

**Comment by politologu** [comment]
because on the center is saying: create a free web...

**Comment by atherdon** [comment]
yeah, but we'll use it more like inspiration, that like a real homepage. i'm working on moving a similar simple style into react. so launchaco version will be available while i'm moving stuff to react...

**Comment by atherdon** [comment]
progress here https://github.com/atherdon/gatsby-first-time

**Comment by politologu** [comment]
@atherdon now is on my local computer 
I implement

Install
Make sure that you have the Gatsby CLI program installed:

npm install --global gatsby-cli
And run from your CLI:

gatsby new gatsby-example-site
Then you can run it by:

cd gatsby-example-site
npm run develop

and done with successfully :)

**Comment by atherdon** [comment]
yeah, i know it :)


On 19-Apr-2018 at 10:03 AM, Qazim Rama wrote:


@atherdon <https://github.com/atherdon> now is on my local computer
I implement

Install
Make sure that you have the Gatsby CLI program installed:

npm install --global gatsby-cli
And run from your CLI:

gatsby new gatsby-example-site
Then you can run it by:

cd gatsby-example-site
npm run develop

and done with successfully :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/frontend/issues/14#issuecomment-382680858>,
or mute the thread
