### ISSUE TITLE
Detailed explanation

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/frontend#2]
### Story behind
Ok, main goal of creating this repository is to separate frontend logic of GroceriStar project with API logic.
Right now, at current project stage it's looks like a mess. Project is simple, but at this stage too - it must be improved. So i dig into different options with question - how i can improve 'flow' when client and server are separated, files have good structure, project have build feature and can be updated/extended easily.
All times, when i read articles I see that only React with webpack provide such kind of functionality. So i decide that in future i'll split front and API into a two different projeccts.

## Big picture
Whole frontend must be implemented and then connected to a GS project.
Design must be improved, pages must load fast, scripts must be organized, minified and combined together. Responsive for sure.

## From what we can start.
Right now we have an ugly homepage. Yep it bad, cause i created it from landing page builder. Lazy and don't want to spend time on it. but content for LP was completed and can be an advantage for a next page creation steps.

To create a brand new, shiny page will be the first task. Did you need my guidance? or you can create it from scratch with some cool design that you'll pick? I mean there a lot of cool homepage designs, where we can grab styles and view. i have a few things to show you - but i want to see what you capable of.

next part **pages**, not related to shopping list and homepage.
right now these pages are inner pages. and they look like a default dashboard with bootstrap styles - and this is how they built. i grab some styles, HTML templates from my previous projects.

right now these pages don't have a one simple UI. right now it just pages, that connected. a lot of people confused about how they can use the product. So it can be different ways to accomplish this problem. I'll want to hear your thoughts first and then explain my vision.

shopping list views. before i just get layouts and js code from TODOMVC and apply it. but it has some troubles with converting a logic. and it was not really optimized to mobiles. so when my friend starts joking about it - i spend few weeks and redo it basically from scratch. i find an HTML framework with styles related to mobile form elements and apply groceristar logic into that element.
Not sure if I want to redo it again. maybe it'll be better to implement a gap between Gs and some other TODO list projects. cause I don't want to reinvent the wheel - better to focus on expanding features of it.

next item will be to understand for me - if some parts of React logic can be copy-pasted and converted into React native, cause I want to build an app in the future.
maybe I need to share with you some design starter kits, that have a lot of predefined pages and can be used in my project.

Tell me what do you think!
I'll extend this task - plan to add screens from current online version - so you'll have all data in one place. will do it later - if I'll see a lot of progress.

**Comment by atherdon** [comment]
@politologu 
Tell me when you'll be able to start?
Do you have any questions to me? 
Is everything is clear?

**Comment by atherdon** [comment]
@politologu 
As I know you at least 4 months and know that you can be distracted by some other things - I'll require an advanced communication, clean plan with dates/deadlines/schedule in order to include you into my projects fast. I want to receive this plan in 5-10 days max and see some commits here. 

We talked a lot and still not have a lot of progress to see or to show. 

Be ready, I'll be "hard" with you, because I think you need this. You bright, but have a lot of things to improve.

Still questions are "pending"

**Comment by politologu** [comment]
@atherdon hey Arthur as for React yet not ready to get started, because I need to learn more deeply about pure javascript, but as for with HTML5, CSS3 Javascript, bootstrap or similarly I am ready. I saw now the new  design homepage is more beautiful than before

**Comment by atherdon** [comment]
@politologu ok, so what will be our plan? and by my opinion, you're more than ready - but somehow - you don;t trust in yourself...

yep, this page is better. but soon one of our designers will finished a custom homepage and we'll redo it again.
